---
# defaults file for roles/auditd_hardening

auditd_buffer_size: 8192
auditd_max_log_file: 30
auditd_log_format: "ENRICHED"
auditd_max_log_file_action: "ROTATE"
auditd_rules_file: "/etc/audit/rules.d/99-hardening.rules"
auditd_conf_file: "/etc/audit/auditd.conf"
