---
- name: Ubuntu hardening
  hosts: servers
  become: true
  pre_tasks:
    - name: Create hardening backup directory
      ansible.builtin.file:
        path: "{{ hardening_backup_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0700"
  roles:
    #- packages
    #- pam_password_policy
    #- mount_hardening
    #- ssh_hardening
    #- auditd_hardening
    #- apparmor_hardening
    #- aide_hardening
    #- sysctl_hardening
    #- nftables_hardening
    - kernel_modules_hardening